apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: url-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: ecr-registry-secret
      containers:
        - name: frontend
          image: 278061313986.dkr.ecr.ap-southeast-2.amazonaws.com/urlplatform-frontend:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
