apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: url-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      imagePullSecrets:
        - name: ecr-registry-secret
      containers:
        - name: api-gateway
          image: 278061313986.dkr.ecr.ap-southeast-2.amazonaws.com/urlplatform-api-gateway:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: USER_SERVICE_URL
              value: "http://user-service:8081"

            - name: URL_SERVICE_URL
              value: "http://url-service:8082"
