apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: url-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: url_platform-user-service:latest
          imagePullPolicy: Never    
          ports:
            - containerPort: 8081
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: url-platform-config
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: url-platform-config
                  key: DB_PORT

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: url-platform-config
                  key: DB_NAME

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: url-platform-secret
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: url-platform-secret
                  key: DB_PASSWORD