apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: url-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: url_platform-api-gateway:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: USER_SERVICE_URL
              value: "http://user-service:8081"

            - name: URL_SERVICE_URL
              value: "http://url-service:8082"